version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
      - GITEA____APP_NAME=XServ Laboratories Internal VCS
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service__NO_REPLY_ADDRESS=git.noreply@i.xserv.dev
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__SMTP_ADDR=mail.i.xserv.dev
      - GITEA__mailer__SMTP_PORT=587
      - GITEA__mailer__FROM=gitea@i.xserv.dev
      - GITEA__mailer__USER=${GITEA__mailer__USER}
      - GITEA__mailer__PASSWD=${GITEA__mailer__PASSWD}
      - GITEA__cron_0X2E_update_0X5F_checker__ENABLED=true
    restart: always
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9002:3000"
      - "22:22"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - gitea
    volumes:
      - ./data/postgres:/var/lib/postgresql/data