services:
  apache:
    build: .
    container_name: apache
    volumes:
      - "/etc/ssl/i.xserv.dev/:/etc/ssl/i.xserv.dev/:ro"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"